<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>
	<ItemGroup>
		<TrimmerRootAssembly Include="TeamServer" />
		<TrimmerRootAssembly Include="DataList" />
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Services\" />
    <Folder Include="Helper\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataList\DataList.csproj" />
  </ItemGroup>

</Project>
